### ISSUE TITLE
Create a small piece of UI to control the learning path 

### ISSUE THREAD

**Issue by arjunmahishi** [fnplus/footsteps-extension#5]
### TODO
- [ ] This would be displayed on all footsteps enabled website on the top-right corner permanently
- [ ] should be extremely translucent to make sure the content underneath can be easily visible
- [ ] should become sold on hover
- [ ] should have buttons to control how this site affects the learning path. Eg: "helpful", "not helpful", "all I needed" something like that
- [ ] should look fine on all kinds of websites. (minimal, generic colors, etc)

### Getting started on this:
Look at the `src/content.js` file. You can modify the dom(the HTML elements) from this file. So, you can directly inject the UI from here. Play around with `content.js` to figure out how this can be done.

**Comment by arjunmahishi** [comment]
Closing this as it is done
